# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for CDG Launcher -- self-contained single exe."""

from PyInstaller.utils.hooks import collect_submodules

hiddenimports = [
    "server",
    "adapters",
    "adapters.chat_to_responses",
    "adapters.responses_to_chat",
    "adapters.tools_adapter",
    "uvicorn",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.http.httptools_impl",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "uvicorn.logging",
    "uvicorn.middleware",
    "uvicorn.middleware.proxy_headers",
    "fastapi",
    "fastapi.openapi",
    "fastapi.middleware",
    "starlette",
    "starlette.routing",
    "starlette.middleware",
    "starlette.middleware.cors",
    "pydantic",
    "pydantic_core",
    "pydantic.deprecated",
    "httpx",
    "socksio",
    "anyio",
    "anyio._backends._asyncio",
    "h11",
    "websockets",
    "websockets.legacy",
    "dotenv",
    "asyncio",
    "logging",
    "queue",
    "uuid",
]

a = Analysis(
    [r"scripts\launcher_pyside6.py"],
    pathex=[r"C:\Users\xxs\Desktop\CDG"],
    binaries=[],
    datas=[
        (r"app_icon.ico", "."),
        (r"app_icon.png", "."),
        (r"codex", "codex"),
    ],
    hiddenimports=hiddenimports + collect_submodules("adapters"),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "tcl",
        "matplotlib",
        "numpy",
        "pandas",
        "PIL",
        "sqlite3",
        "test",
        "tests",
        "unittest",
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="CDG Launcher",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=r"app_icon.ico",
)
